name: Verificacion de pruebas
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ejecutar pruebas
        working-directory: twitter-frontend
        run: |
          npm i
          npm test